### ISSUE TITLE
How to integrate into django manage shell

### ISSUE THREAD

**Issue by flisky** [ivanov/vim-ipython#11]
Hi ivanov,

I'm very interested in howto integrate this plugin into django shell management command.

Basically, django uses ipython (if ipython is present) as interactive shell for enhancement. And django offers a hook (by subclass) to customize this behavior. Please see django changeset [#14895](https://code.djangoproject.com/changeset/14895).

My question is that could we get the ipython running information, something like  --existing --shell=xxx --iopub=xxx --stdin=xxx --hb=xxx, which is required by this plugin(?) without running qtconsole? If it couldn't, how to embed qtconsole in the django manage shell?

Hope it's a right place to ask this question. Sorry for my poor English.
And please let me know if it's a stupid question, since there is an old way: just setup django environment when qtconsole starts up, which I do not really like.

Thanks,

**Comment by davnustratbac** [comment]
testing if this thread will allow comments after closing :)

**Comment by davnustratbac** [comment]
Hi guys, not sure if this is useful or if im out of date here, but ive found a partial solution to this issue, im using django-extensions and ipython installed in the virtualenv. i have then added 'console' to the django extensions params as ... 

IPYTHON_ARGUMENTS = [  
    'console'  
]     

in django settings.py

 after firing up vim and making sure all vim-ipython requiremets were met && i was editing a .py file
i could send to the ipython session and had access to the dynamically loaded ipython session into django, I have not had chance to test all the functionality but it appears to be working in a basic manner. would be interested to hear if this helps
Ipython  3.2.1
django 1.8
django-extensions 1.5.7
vim 7.4.827 
Cheers D
