### ISSUE TITLE
Using over ssh on Amazon Ec2

### ISSUE THREAD

**Issue by hrishikeshvganu** [ivanov/vim-ipython#142]
I'm trying to setup vim-ipython on an Ec2 AWS instance and use it by ssh into the remote instance. The ipython notebook and vim are both installed on the remote machine. The ctrl-s combination or the <F5> key don't work for me.

**Comment by ivanov** [comment]
Hey there @hrishikeshvganu, I'm going through old issues and it seems to me that it makes sense to close this one. Sorry you had trouble with vim-ipython... It seems like you hit one of the [known issues](https://github.com/ivanov/vim-ipython#known-issues) which needed the following command in your .bashrc/.bash_profile: `stty stop undef # to unmap ctrl-s`

Happy hacking! :bowtie:
