### ISSUE TITLE
Getting vim-ipython to run on Windows 7 using Anaconda2.0.0 (32-bit) (Python2.7, IPython2.1.0, etc. distro)

### ISSUE THREAD

**Issue by 10p10110111xxi11p00100100** [ivanov/vim-ipython#95]
Hello, another Windows user here with Windows-related (?) problems,

In short: installation of vim-ipython is successful, but calling `:IPython` fails at specific Python libraries (ctypes, zmq?). Similar bugs were reported before [#34](https://github.com/ivanov/vim-ipython/issues/34), [#21](https://github.com/ivanov/vim-ipython/issues/21), [#20](https://github.com/ivanov/vim-ipython/issues/20), but I am not certain if this is the same kind of bug or a problem of the Python distribution (Anaconda) and incorrect packaging of IPython, zmq, etc.

OS: Win7 (64 bit)
Vim: gVim 7.4 (2013 Aug 10, compiled Aug 10 2013 14:38:33)
Python stack: Python 2.7.6 |Anaconda 2.0.0 (32-bit)| (default, May 27 2014, 15:05:55) [MSC v.1500 32 bit (Intel)]
IPython: IPython 2.1.0
IPython and Python are installed together by Anaconda Python distribution and registered in Windows Registry.
vim-ipython: installed with Vundle (automatically gets newest Git repo or updates to the newest; based on Pathogen)

Checking if Windows Registry is correctly used:
Running "`import os; print os.__file__`" in IPython or Python.exe (on CMD.exe) returns:

```
C:\Anaconda\lib\os.pyc
```

Running "`:py import os; print os.__file__`" on gVim commandline returns:

```
C:\Anaconda\lib\os.pyc
```

The problem occurs when opening a Python file (.py) with gVim and then running ":IPython" on gVim commandline:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 83, in km_from_string
  File "C:\Anaconda\lib\site-packages\IPython\kernel\__init__.py", line 4, in <module>
    from . import zmq
  File "C:\Anaconda\lib\site-packages\IPython\kernel\zmq\__init__.py", line 14, in <module>
    check_for_zmq('2.1.11', 'IPython.kernel.zmq')
  File "C:\Anaconda\lib\site-packages\IPython\utils\zmqrelated.py", line 35, in check_for_zmq
    import zmq
  File "C:\Anaconda\lib\site-packages\zmq\__init__.py", line 41, in <module>
    _libzmq = ctypes.cdll.LoadLibrary(bundled[0])
  File "C:\Anaconda\Lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Anaconda\Lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
```

Running Python.exe on CMD.exe:

```
>>>import ctypes
>>> ctypes.__version__
'1.1.0'

>>> import zmq
>>> zmq.__version__
'14.3.0'
>>> zmq.__path__
['C:\\Anaconda\\lib\\site-packages\\zmq']

>>> import IPython
>>> IPython.__version__
'2.1.0'
>>> IPython.__path__
['C:\\Anaconda\\lib\\site-packages\\IPython']
```

What can I do to be able to run `:IPython` in gVim commandline? Please be detailed, as I do not have a lot of experience installing and configuring Microsoft Visual Studio or Windows SDK. I could install Windows SDK and get `mt.exe` running, but it returned only errors when trying to "sign" the files. From previous issue reports it is not clear which files (gVim.exe, python27.dll, .pyd, .pyc) should be "signed" with which signatures. Is there a different 32 and 64 bit version of `mt.exe`?

**Comment by aronla** [comment]
I'm having the exact same issue, but can't get the solution above to work. Could this be the reason: when using the "XN Resource Editor" and importing the user resource, I can't get it to say "XP Theme Manifest" anymore? Does the node have to have this exact name?

I'd appreciate any help, this is driving me nuts! :)

**Comment by chiefenne** [comment]
I am having the same status as @aronla.
Almost same nuts driving issue :)
